rule_files:
  - "recording-rules.yml"


global:
  scrape_interval: 15s  # הגדירי כל כמה זמן פרומיתיוס ידגום נתונים
  evaluation_interval: 15s  # כל כמה זמן להעריך חוקים


scrape_configs:
  - job_name: 'ec2-node-exporters'
    ec2_sd_configs:
      - region: us-east-1
        port: 9100
        filters:
          - name: tag:role
            values: [statuspage]
          - name: tag:owner
            values: [meitaveini]
    relabel_configs:
      - source_labels: [__meta_ec2_private_ip]
        regex: (.*)
        target_label: __address__
        replacement: "${1}:9100"
